name: Docker Release

run-name: Docker Release ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      disable_cache:
        description: "Disable Docker build cache"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: devcontainer

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      build_number: ${{ steps.semantic.outputs.new_release_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          semantic_version: 23
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1

      - name: Set lowercase repository owner
        id: repo
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          context: .
          platforms: linux/amd64
          build-args: |
            INIT_SCRIPT_PATH=init_scripts/init_full.sh
            BASE_IMAGE=ubuntu:rolling
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ steps.repo.outputs.owner }}/${{ env.IMAGE_NAME }}:v${{ steps.semantic.outputs.new_release_version }}
          cache-from: ${{ github.event.inputs.disable_cache != 'true' && 'type=gha' || '' }}
          cache-to: ${{ github.event.inputs.disable_cache != 'true' && 'type=gha,mode=max,retention-days=2' || '' }}

      - name: Generate build summary
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "## Docker Release Summary" >> $GITHUB_STEP_SUMMARY
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "- **Image**: ${{ env.REGISTRY }}/${REPO_OWNER}/${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags**: latest, v${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Version**: v${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Docker image built and pushed successfully!" >> $GITHUB_STEP_SUMMARY

